# Generated by Django 4.0 on 2022-11-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='project/default.png')),
                ('live_url', models.URLField(blank=True, null=True)),
                ('code_url', models.URLField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
