# Generated by Django 4.0 on 2022-11-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_code_url_alter_project_live_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='project/default.png', null=True, upload_to='project/'),
        ),
    ]
